# Generated by Django 4.1.4 on 2022-12-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_date', models.DateField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('collected', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
